/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ckbuycsuhixyuuqslgbf"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrYnV5Y3N1aGl4eXV1cXNsZ2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5OTcyMjUsImV4cCI6MjA3NjU3MzIyNX0.vPQ-Sj9p5PrT-xG8CUPUDt5APWsl_Bj-eFgou_nde_0"